version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPWD}
    ports:
      - 27017:27017
      
    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESSPWD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOPWD}
      ME_CONFIG_MONGODB_URL: mongodb://username:${MONGOPWD}@IP:27017/
      ME_CONFIG_SITE_COOKIESECRET: ewq456
      ME_CONFIG_SITE_SESSIONSECRET: 132aabc
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: local