version: '3.7'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    container_name: docker-elk_kibana
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: '["http://****:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: "****"
      monitoring.ui.container.elasticsearch.enabled: true